import { USState, PromptTemplate } from './types'

export const US_STATES: USState[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'District of Columbia' },
]

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: '1',
    category: 'Employment Law',
    title: 'Wrongful Termination Rights',
    prompt: 'Explain my rights under [STATE] wrongful termination laws. What protections do I have if I believe I was fired unfairly?',
    icon: 'Briefcase',
  },
  {
    id: '2',
    category: 'Employment Law',
    title: 'Wage and Hour Violations',
    prompt: 'What are my rights regarding overtime pay and minimum wage in [STATE]? How do I report violations?',
    icon: 'Briefcase',
  },
  {
    id: '3',
    category: 'Real Estate',
    title: 'Landlord-Tenant Laws',
    prompt: 'What are the landlord-tenant laws in [STATE]? What are my rights as a tenant regarding rent increases, evictions, and security deposits?',
    icon: 'House',
  },
  {
    id: '4',
    category: 'Real Estate',
    title: 'Security Deposit Rights',
    prompt: 'Under [STATE] law, when must my landlord return my security deposit? What deductions are they allowed to make?',
    icon: 'House',
  },
  {
    id: '5',
    category: 'Criminal/Traffic',
    title: 'Traffic Stop Rights',
    prompt: 'What are my rights if I\'m pulled over by police in [STATE]? What should I do and say?',
    icon: 'Siren',
  },
  {
    id: '6',
    category: 'Criminal/Traffic',
    title: 'DUI Consequences',
    prompt: 'What are the penalties and consequences for a first-time DUI in [STATE]? What are my options?',
    icon: 'Siren',
  },
  {
    id: '7',
    category: 'Family Law',
    title: 'Child Custody Laws',
    prompt: 'Explain child custody laws in [STATE]. What factors do courts consider when determining custody arrangements?',
    icon: 'Users',
  },
  {
    id: '8',
    category: 'Family Law',
    title: 'Divorce Process',
    prompt: 'What is the divorce process in [STATE]? What are the residency requirements and grounds for divorce?',
    icon: 'Users',
  },
  {
    id: '9',
    category: 'Business Law',
    title: 'LLC Formation',
    prompt: 'How do I form an LLC in [STATE]? What are the requirements, costs, and ongoing obligations?',
    icon: 'Buildings',
  },
  {
    id: '10',
    category: 'Business Law',
    title: 'Contract Basics',
    prompt: 'What makes a contract legally binding in [STATE]? What elements must be present for a contract to be enforceable?',
    icon: 'Buildings',
  },
  {
    id: '11',
    category: 'Consumer Protection',
    title: 'Credit Report Disputes',
    prompt: 'How do I dispute errors on my credit report? What are my rights under the Fair Credit Reporting Act?',
    icon: 'ShieldCheck',
  },
  {
    id: '12',
    category: 'Consumer Protection',
    title: 'Debt Collection Rights',
    prompt: 'What are my rights when dealing with debt collectors? What actions are prohibited under the Fair Debt Collection Practices Act?',
    icon: 'ShieldCheck',
  },
  {
    id: '13',
    category: 'Health Law',
    title: 'HIPAA Rights',
    prompt: 'What are my rights under HIPAA? How is my medical information protected and when can it be shared?',
    icon: 'FirstAid',
  },
  {
    id: '14',
    category: 'Health Law',
    title: 'Medical Bill Disputes',
    prompt: 'How can I dispute incorrect medical bills? What are my options if I can\'t afford to pay?',
    icon: 'FirstAid',
  },
  {
    id: '15',
    category: 'Tax Law',
    title: 'State Tax Deductions',
    prompt: 'What are the common tax deductions available in [STATE]? How can I minimize my state income tax liability?',
    icon: 'Receipt',
  },
  {
    id: '16',
    category: 'Immigration',
    title: 'Green Card Process',
    prompt: 'What is the process for obtaining a green card? What are the different categories and requirements?',
    icon: 'Passport',
  },
]

export const LEGAL_DISCLAIMER = `**Important Legal Disclaimer**: This is legal information, not legal advice. The responses generated are for informational purposes only and should not be considered legal advice. Laws vary by jurisdiction and individual circumstances. Always consult with a qualified, licensed attorney for advice on your specific situation.`

export const CATEGORY_ICONS: Record<string, string> = {
  'Employment Law': 'Briefcase',
  'Real Estate': 'House',
  'Criminal/Traffic': 'Siren',
  'Family Law': 'Users',
  'Business Law': 'Buildings',
  'Consumer Protection': 'ShieldCheck',
  'Health Law': 'FirstAid',
  'Tax Law': 'Receipt',
  'Immigration': 'Passport',
}
