// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRn9TbPVymGiXSF2BEM7wxQxrPxmaUJ8',
    appId: '1:367506430362:web:43d854376f10eb2b1e8223',
    messagingSenderId: '367506430362',
    projectId: 'jeffery-friendly-pocket-law',
    authDomain: 'jeffery-friendly-pocket-law.firebaseapp.com',
    storageBucket: 'jeffery-friendly-pocket-law.firebasestorage.app',
    measurementId: 'G-14L0SPDG8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGObS0HqbDLIyr24WwO5pPW64sKb_nK0A',
    appId: '1:367506430362:android:6bd7530f3c0607ee1e8223',
    messagingSenderId: '367506430362',
    projectId: 'jeffery-friendly-pocket-law',
    storageBucket: 'jeffery-friendly-pocket-law.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Z_9Ncc_Z_Ab4_APnGBhjc5rSldirlio',
    appId: '1:367506430362:ios:67ebe39dda6a82381e8223',
    messagingSenderId: '367506430362',
    projectId: 'jeffery-friendly-pocket-law',
    storageBucket: 'jeffery-friendly-pocket-law.firebasestorage.app',
    iosBundleId: 'com.example.androidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRRn9TbPVymGiXSF2BEM7wxQxrPxmaUJ8',
    appId: '1:367506430362:web:a653998a925a33041e8223',
    messagingSenderId: '367506430362',
    projectId: 'jeffery-friendly-pocket-law',
    authDomain: 'jeffery-friendly-pocket-law.firebaseapp.com',
    storageBucket: 'jeffery-friendly-pocket-law.firebasestorage.app',
    measurementId: 'G-HXFS617JSZ',
  );

}